name: Build Develop

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.8 }
      - name: Build server jar
        run: |
          ./gradlew :server:jar
      - name: Upload server jar
        uses: actions/upload-artifact@v2
        with:
          name: dcs-server.jar
          path: server/build/libs/dcs-server.jar
      - name: Build client jar
        run: |
          ./gradlew :client:jar
      - name: Upload client jar
        uses: actions/upload-artifact@v2
        with:
          name: dcs-server.jar
          path: client/build/libs/dcs-client.jar